### PR TITLE
Fix a typo with repo.py

### PR DESCRIPTION
**Pull request by psyking841**
I was using the master branch, but it broke my code because "_get_from_repo" return None for some reason. Then I took some time to debug and realized there is a typo inside from_repo. Then I found the problem: the 'url' for _get_from_repo should be a file name, which is fname!

In addition, in my early debugging, I though it was because "_get_from_repo" is not able to create "/tmp" folder. So I deleted '/tmp'. By deleting it, the mktempfile will generate a folder in the system's default temp folder which varies from platform to platform. This could avoid future permission issue.

I also put the importing of boto3 and botocore to the function who uses them. Because for a person like me, who uses this library in IBM Cloud, I don't want to import them. 

Let me know what you think.

Thanks @flaper87 @yanivoliver

### CODE REVIEW

**Comment by ljakimczuk** [comment]
Hi @yanivoliver @psyking841 @avorima


@psyking841  could you elaborate more on the problem? What was the structure of the `index.yaml`? The `url` didn't seem a problem to me, but it's very likely I haven't checked all the use cases. However, this changes brakes some use-cases.

The `url` comes from looping through the `urls` in the `index.yaml`, where the `repo_url` comes from parsing the repository given in the parameters (corresponding to the repository configured with Helm). The problem arises when the `urls` in the `index.yaml` are relative URLs of the charts (possibly having more directories in path than just a `fname`), not the absolute URLs, e.g.:

`apiVersion: v1
entries:
  test:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2018-11-24T10:58:52.2307277Z"
    description: XXXXX
    digest: xxxxxxxxxxx
    name: vewd-mailhog
    urls:
    - charts/test-0.1.0.tgz
    version: 0.1.0
generated: "2018-11-24T10:58:58Z"
`
In the example the repository URL could be something like `https://test.example.com/stable` as configured in the Helm, though the `index.yaml` clearly points that you have to search for a chart under the `charts/` directory.
That's why I'm passing the possibly relative `url` to the `_get_from_repo` and later on it's checked against the `repo_url` (and joined if necessary):

`
    if repo_url not in file_url:
        file_url = os.path.join(repo_url, file_url)
`

Using `fname` will omit the `charts/` part. Of course, I have no problem with using the `fname`, but the other functions should be adjusted. But since charts are downloaded based on the `urls` in the `index.yaml` I guess we could try to find the most common combinations of the indices and how the `urls` are presented and then adjust the solution?

This is related to PR #36

**Comment by psyking841** [comment]
It seems my fix broke others code but if we put the url back it breaks
mine. I am traveling these days but I will find sometime at night when I
got the access to my computer.

**Comment by avorima** [comment]
@psyking841  Hey, sorry I didn't check the other pull requests. I wouldn't have simply made mine if I'd known this was just recently changed.

@ljakimczuk My problem comes from exactly what you described. I have an `index.yaml` with URLs that can just be appended to `repo_url` and be valid.

I have a few ideas to make things work for both cases. I'll push them to my PR if that's okay.
Probably not very soon though.

**Comment by ljakimczuk** [comment]
@avorima it would be good to also understand the second case since using the `urls` from the `index.yaml` is, I would call it, canonical. The URLs could be absolute, then should be used as is, or relative, then should be prepend with the repository URL, both are simple operations and the Helm does it the same way as far as I know.

Again, there may be few cases when there might be a problem, e.g., when the `index.yaml` have wrong paths in the URLs and prepending it with the repository gives the wrong absolute URL (then it's rather the repository problem, since index does not now the correct location). The other scenario I could think of is when the repository was setup with the `--url` equal to, e.g. the `http://localhost` (or simply a different URL than the actual repository URL known to Helm), giving different absolute urls and causing the mentioned `if` to fail - then probably it's the `if` what should be changed. 

Again, it would be the best to have some insight into the problem since not splitting the `urls` from the `index.yaml` was intentional, the index and its URLs is something the whole process depends on.

**Comment by ljakimczuk** [comment]
To avoid the case where absolute URL known to Helm (the same should be given to the `from_repo`) is different than the absolute URL known to the repository (`urls` of the `index.yaml`) this if:

```
if repo_url not in file_url:
file_url = os.path.join(repo_url, file_url)
```

could be changed to something like (or something similar):

```
# for S3 it would be ('s3://')
if file_url.startswith('http'):
file_url = os.path.join(repo_url, file_url)
```

**Comment by psyking841** [comment]
@ljakimczuk @avorima 
Sorry for the late reply. I just checked the index.yaml I have in my Helm repo, we have absolute paths under "urls" tag. From what you described, the original code should have worked with absolute paths. I still don't know why changing from url to fname is working for me (I might forget, it's been a while.) Anyway, I agree we need a better way to deal with related paths and absolute paths.

**Comment by psyking841** [comment]
@ljakimczuk @avorima 
All right, I spent sometime debugging the old code (that before I made the changes), and I found 

'''if repo_url not in file_url:'''

is not working properly, when file_url has different appendix from repo_url. In my case, the file_url has a port in the url address but repo_url does not! So it will run into this if statement and appends the repo_url again!

I also verified @ljakimczuk pull request #37, it works for me now with url :)

**Comment by ljakimczuk** [comment]
@psyking841 great! Thank you for checking this! :)

**Pull request merged**
